export const PostDatas = [
    {
        img_src: 'public/images/Buoi_1/buoi_1_1.png',
        description: 'Truy cập W3S đọc phần HTML Tutorial, tìm hiểu các thẻ liệt kê trong ảnh dưới đây (trừ phần HTML CSS) và trình bày rõ ràng theo các ý bằng 1 file html',
        url_href: 'home/Lesson_1/excercise_1/',
        title: 'Bài 1 buổi 1',
    },
    {
        img_src: 'public/images/Buoi_2/buoi_2_1.png',
        description: 'Sử dụng file TestLab1.html, thực hiện định style theo 3 kiểu inline, internal, external',
        url_href: 'home/Lesson_2/excercise_1/',
        title: 'Bài 1 buổi 2',
    },
    {
        img_src: 'public/images/Buoi_2/buoi_2_2.png',
        description: 'Tạo trang web đúng mẫu theo các liên kết sau',
        url_href: 'home/Lesson_2/excercise_2/',
        title: 'Bài 2 buổi 2',
    },
    {
        img_src: 'public/images/Buoi_2/buoi_2_3.png',
        description: 'Tạo trang web, các thẻvà CSS các thẻtương ứng đểcó kết quảnhư sau',
        url_href: 'home/Lesson_2/excercise_3/',
        title: 'Bài 3 buổi 2',
    },
    {
        img_src: 'public/images/Buoi_2/buoi_2_4.png',
        description: 'Trình bày và định dạng trang web như mẫu văn bản đính kèm (phải dùng class, ID',
        url_href: 'home/Lesson_2/excercise_4/',
        title: 'Bài 4 buổi 2',
    },
    {
        img_src: 'public/images/Buoi_3/buoi_3_2.png',
        description: 'Trình bày trang baomoi.com (phần hình ảnh dưới) chú ý thực hiện chính xác menu, bố cục chia cột và các hiệu ứng xảy ra khi hover chuột vào (hình ảnh, link)',
        url_href: 'home/Lesson_3/excercise_2/',
        title: 'Bài 2 buổi 3',
    },
    {
        img_src: 'public/images/midterm.png',
        description: 'Bài tập 30% cô gửi trên Teams',
        url_href: 'home/Lesson_4/mid_term/',
        title: 'Kiểm tra 30%',
    },
    {
        img_src: 'public/images/Buoi_4/bai_1.png',
        description: 'Bài 1 buổi 4',
        url_href: 'home/Lesson_4/excercise_1/',
        title: 'Kiểm tra 30%',
    },
    {
        img_src: 'public/images/Buoi_4/bai_2.png',
        description: 'Bài 2 buổi 4',
        url_href: 'home/Lesson_4/excercise_2/',
        title: 'Bài 2 buổi 4',
    },
    {
        img_src: 'public/images/Buoi_4/bai_3.png',
        description: 'Bài 1 buổi 4',
        url_href: 'home/Lesson_4/excercise_3/',
        title: 'Bài 3 buổi 4',
    },
    {
        img_src: 'public/images/Buoi_4/bai_4.png',
        description: 'Bài 4 buổi 4',
        url_href: 'home/Lesson_4/excercise_4/',
        title: 'Bài 4 buổi 4',
    },
    {
        img_src: 'https://images.pexels.com/photos/167682/pexels-photo-167682.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        description: 'Bài 1 buổi 5',
        url_href: 'home/Lesson_5/excercise_1/',
        title: 'Bài 1 buổi 5',
    },
    {
        img_src: 'https://images.pexels.com/photos/167682/pexels-photo-167682.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        description: 'Bài 2 buổi 5',
        url_href: 'home/Lesson_5/excercise_2/',
        title: 'Bài 2 buổi 5',
    },
    {
        img_src: 'https://images.pexels.com/photos/167682/pexels-photo-167682.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        description: 'Bài 3 buổi 5',
        url_href: 'home/Lesson_5/excercise_3/',
        title: 'Bài 3 buổi 5',
    },
]